services:
  db:
    image: mariadb:10.4
    ports:
      - 8306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - 'db_data:/var/lib/mysql'
      - 'db_backup:/backup'
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: tacotuesday
    networks:
      - site

  admin:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - site

  wp:
    build:
      context: ./docker
      dockerfile: wp.Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./docker/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./app:/var/www/html
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./favicon.ico:/var/www/html/favicon.ico
      - ./data/uploads:/var/www/html/wp-content/uploads
      # * Make sure that the paths here match (a) the actual path to the relevant folders and (b) the eventual server path to those folders
      - ../wp-theme-starter:/var/www/html/wp-content/themes/project1-theme
      - ../gutestrap:/var/www/html/wp-content/plugins/gutestrap
      - ../wp-image-focal-point:/var/www/html/wp-content/plugins/wp-image-focal-point
      # - ../app:/var/www/html/wp-content/
    depends_on:
      - db
    links:
      - db
    environment:
      DB_NAME: wordpress
      DB_USER: root
      DB_PASSWORD: tacotuesday
      DB_HOST: db
      WP_DEBUG: 1
      WP_DEBUG_LOG: 1
      WP_DEBUG_DISPLAY: 1
      WP_TABLE_PREFIX: "wp_"
      PROD_URL: "https://project1.com"
      DEV_URL: "http://local.wpthemestarter.ca:8000"
      PROD_PLUGINS: "better-wp-security really-simple-ssl breeze"
      DEV_PLUGINS: "debug-bar debug-bar-actions-and-filters-addon health-check"
    networks:
      - site

volumes:
  db_data: # store database into a volume so that we can pause the containers
  db_backup:

networks:
  site:
