version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 8306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: admin

  wp:
    build:
      context: ./docker
      dockerfile: wp.Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./docker/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./app:/var/www/html
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./favicon.ico:/var/www/html/favicon.ico
      # * Make sure that the paths here match (a) the actual path to the theme folder and (b) the eventual server path to the theme folder
      - ../theme:/var/www/html/wp-content/themes/project1-theme
    depends_on:
      - db
    links:
      - db
    environment:
      DB_NAME: wordpress
      DB_USER: root
      DB_PASSWORD: admin
      DB_HOST: db
      WP_DEBUG: 1
      WP_DEBUG_DISPLAY: 1
      WP_TABLE_PREFIX: "wp_"
      LIVE_URL: https://project1.com
      DEV_URL: http://dev.project1.com

volumes:
  db_data: # store database into a volume so that we can pause the containers